package com.sportclubai.core.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Login : Screen("login")
    object RegisterClub : Screen("register_club")
    object Dashboard : Screen("dashboard")
    object Students : Screen("students")
    object AddStudent : Screen("add_student")
    object StudentProfile : Screen("student_profile/{studentId}")
    object EditStudent : Screen("edit_student/{studentId}")
    object Attendance : Screen("attendance")
    object AttendanceSummary : Screen("attendance_summary")
    object Payments : Screen("payments")
    object CreatePayment : Screen("create_payment")
    object Coaches : Screen("coaches")
    object AddCoach : Screen("add_coach")
    object CoachDetail : Screen("coach_detail/{coachId}")
    object EditCoach : Screen("edit_coach/{coachId}")
    object Classes : Screen("classes")
    object CreateClass : Screen("create_class")
    object ClassDetail : Screen("class_detail/{classId}")
    object EditClass : Screen("edit_class/{classId}")
    object Messages : Screen("messages")
    object Chat : Screen("chat/{type}/{id}")
    object AITraining : Screen("ai_training")
    object Calendar : Screen("calendar")
    object Notifications : Screen("notifications")
    object NotificationSettings : Screen("notification_settings")
    object NotificationDetail : Screen("notification_detail/{notificationId}") {
        fun createRoute(notificationId: String) = "notification_detail/$notificationId"
    }
    object Reports : Screen("reports")
    object Settings : Screen("settings")
    object CoachProfile : Screen("coach_profile/{coachId}")
    object StudentPanel : Screen("student_panel")
    object MyProfile : Screen("my_profile")
    object MyAttendance : Screen("my_attendance")
    object MyPayments : Screen("my_payments")
    object MySchedule : Screen("my_schedule")
    object MyMessages : Screen("my_messages")
    object MyTraining : Screen("my_training")
    object MyBeltProgress : Screen("my_belt_progress")
    object MySettings : Screen("my_settings")
    object MyNotifications : Screen("my_notifications")
    object ParentPanel : Screen("parent_panel")
    object Competition : Screen("competition")
    object BeltExams : Screen("belt_exams")
    object Gallery : Screen("gallery")
    object Documents : Screen("documents")
    object About : Screen("about")
}
